export const validFields: Record<string, string[]> = {
  user: [
    'id',
    'email',
    'password',
    'fullName',
    'adress',
    'city',
    'country',
    'wallet',
    'role',
    'isAdmin',
    'admin',
    'teacher',
    'student',
    'createdAt',
    'updatedAt',
  ],
  admin: ['id', 'isSupper', 'userId'],
  student: [
    'id',
    'user',
    'userId',
    'CoursProgress',
    'favoritCourses',
    'TeacherReview',
    'CoursReview',
  ],
  coursProgress: [
    'id',
    'student',
    'studentId',
    'cours',
    'coursId',
    'stage',
    'isFinished',
    'createdAt',
    'updatedAt',
  ],

  course: [
    'id',
    'teacher',
    'teacherId',
    'title',
    'description',
    'published',
    'price',
    'hasCertificate',
    'coursProgress',
    'Student',
    'courseReviews',
    'subCategories',
    'courseSteps',
    'createdAt',
    'updatedAt',
  ],

  coursReview: [
    'id',
    'course',
    'courseId',
    'student',
    'studentId',
    'createdAt',
    'updatedAt',
  ],

  courseStep: [
    'id',
    'title',
    'content',
    'Course',
    'courseId',
    'video',
    'createdAt',
    'updatedAt',
  ],

  video: [
    'id',
    'duration',
    'title',
    'description',
    'courseStep',
    'courseStepId',
  ],

  category: ['id', 'name', 'subCategories'],

  subCategory: ['id', 'name', 'Course', 'courseId', 'category', 'categoryId'],

  teacher: ['id', 'user', 'userId', 'courses', 'skills', 'teacherReview'],

  skills: ['id', 'teacher', 'teacherId', 'pourcent', 'createdAt', 'updatedAt'],

  teacherReview: [
    'id',
    'teacher',
    'teacherId',
    'student',
    'studentId',
    'createdAt',
    'updatedAt',
  ],
};
