# =========== Testing categories routes via REST client =========== #
@host = http://localhost:5000/api/students
@query = name[startsWith]=S&page=1&limit=3
@body = {"isStudent":false}

#"40261062-7cc2-4e7b-829d-ea0f8729257c" User ID
#"58885f7a-92f5-4287-8264-ab4ade63a759" User ID
### Get all categories
GET {{host}}
### Get a category by ID 
GET {{host}}/33bdee5b-e520-41ed-962a-d45e017b7706
### Delete a category by ID
DELETE {{host}}/121a86ff-69e6-422e-8605-5ddaf8ad83f1
### Update a category
PUT {{host}}/23fcd917-d5df-4d86-99ef-ada7417cd02d
Content-Type: application/json

{{body}}
### Create a category
POST {{host}}/
Content-Type: application/json

{{body}}
